In [18]:
import pandas as pd

In [42]:
def load_id_file(filepath):
    f = open(filepath, 'r')
    lines = f.readlines()
    f.close() #Free up this resource -> it is locked for others as long as it is open by you

    file_ids = {'id' : [item.strip() for item in lines]}
        
    return(file_ids)
    
"""
#ids = {line.strip() : len(ids) for line in f.readlines()} #strip out new, trailing line space (\n)
n = 0
for item in f.readlines():
    ids[item.strip()] = n
    n += 1
"""

'\n#ids = {line.strip() : len(ids) for line in f.readlines()} #strip out new, trailing line space (\n)\nn = 0\nfor item in f.readlines():\n    ids[item.strip()] = n\n    n += 1\n'

In [43]:
id_lookup = load_id_file('CP2_datasets/football/football.ids')

In [46]:
IDs = pd.DataFrame(id_lookup)
IDs

            id
0    372949912
1    206121850
2    209225665
3    230845588
4    366796169
5    187572312
6    375832633
7    374661980
8    240807110
9    241065455
10   636286824
11   250803835
12   280665816
13   726848270
14    51597791
15   627491854
16   353791374
17   232313241
18   265982289
19   130960283
20    51443410
21   238264016
22   471332737
23    32834791
24   143884558
25   549112918
26   484340979
27   633943195
28   287202982
29   303126905
..         ...
218  283771561
219  166767883
220  367971451
221  304182081
222  161745170
223  252753618
224  710064516
225  217423296
226  225418717
227  245014679
228  507489702
229  472185221
230  311757784
231   44335177
232  471271538
233  283894108
234  637041761
235  294809172
236  343626364
237  465811969
238  209185477
239  263099844
240   32329366
241  150632123
242  293467348
243  282634845
244  221850321
245   50711514
246  406971569
247  308422676

[248 rows x 1 columns]

In [ ]:
# function to read in mtx file (not ids now)

def read_features(filepath):